version: 2 # use CircleCI 2.0
jobs: # A basic unit of work in a run
  build: # runs not using Workflows must have a `build` job as entry point 
    # directory where steps are run
    working_directory: ~/binaries
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.7
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}      
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip && pip install -r requirements.txt
      - run:
          name: Clone latest arendst/tasmota
          command: git clone --branch=development --depth=1 "https://github.com/arendst/Tasmota.git" 
      - run: ls -al
      - run:
          name: Copy overrides
          command: cp platformio_override.ini $CIRCLE_WORKING_DIRECTORY/Tasmota/ && cp user_config_override.h $CIRCLE_WORKING_DIRECTORY/Tasmota/tasmota/
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
    # deploy:
    #   steps:
    #     - checkout
    #     - run:
    #         name: Deploy Binaries
    #         command: |
    #           git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master